Public Module Constants
    'Public Const connectionString As String = "Data Source=:memory:;Version=3;New=True;"
    Public Const CTP As String = "CTP"
    Public Const CTP1 As String = "CTP_1"
    Public Const CTP2 As String = "CTP_2"
    Public Const skinscol As String = "SkinsCollected"
    Public Const skinsearn As String = "SkinsEarned"
    Public Const skinsextr As String = "SkinsExtra"
    Public Const Paid As String = "Paid"
    Public Const ctp1collected As String = "CTP1Collected"
    Public Const ctp2collected As String = "ctp2collected"
    Public Const ctp1earned As String = "ctp1earned"
    Public Const ctp2earned As String = "ctp2earned"
    Public Const ctp1extra As String = "ctp1extra"
    Public Const ctp2extra As String = "ctp2extra"
    Public Const kitty As String = "Kitty"
    Public Const earned As String = "$Earn"
    Public Const skinamt As String = "$Skins"
    Public Const skinnum As String = "#Skins"
    Public Const skin As String = "Skins"
    Public Const skinpmt As String = "Skin"
    Public Const closest As String = "Closest"
    Public Const closestamt As String = "$Closest"
    Public Const points As String = "Points"
    Public Const teampoints As String = "Team_Points"
    Public Const opponent As String = "Opponent"
    Public Const datecon As String = "Date"
    Public Const Clear As String = "Clear"
    Public Const Detail As String = "Detail"
    Public Const Comment As String = "Comment"
    Public Const Desc As String = "Desc"
    Public Const Earnedcon As String = "Earned"
    Public Const Name As String = "Name"
    Public Const Player As String = "Player"
    Public Const Method As String = "Method"
    Public Const Team As String = "Team"
    'fields with (Number) are key fields
    'field width-read only-Tab Stop-MiddleRight
    Public Const cPat20 = "25-false-true-mr"
    Public Const cPat30 = "30-false-true-mr"
    Public Const cPat40 = "40-false-true-mr"
    Public Const cPat40nt = "40-true-false-mr"
    Public Const cPat50 = "50-false-true-mr"
    Public Const cPat50nt = "50-true-false-mr"
    Public Const cPathole = "40-false-true-ml"
    Public Const cPat60 = "60-false-true-mc"
    Public Const cPat70nt = "70-true-false-mr"
    Public Const cPatMeth = "80-false-true-mc"
    Public Const cPat120 = "120-false-true-ml"
    Public Const cPat170 = "170-false-false-ml"
    Public Const cPat170nt = "170-true-false-ml"

    Public Const cBaseScoreCard As String = "Player(1)-cPat170,Method-cPatMeth,Team,Group(3),Holes,Hdcp-cPat40nt"
    Public Const cSkinsFields As String = "Skin Paid,Skins-cPat40nt"
    Public Const cCTPFields As String = "CTP Paid"
    Public Const cStatsFields As String = "Eagles-cPat40nt,Birdies-cPat60nt,Pars-cPat40nt,Bogeys-cPat40nt,DoubleBogeys-cPat40nt,Others-cPat40nt"
    Public Const cMatchFields As String = "Team-cPat40nt,Player-cPat170,Out_Gross-v,PHdcp-cPat40nt,Out_Net-cPat40nt,Points-cPat40nt,Team_Points-cPat50nt,Opponent-cPat170nt"
    Public Const cNewMatchFields As String = "Opponent-cPat170nt,Team_Net-cPat40nt,Points-cPat40nt,Team_Points-cPat50nt"
    Public Const cEarningsFields As String = "$Earn-cPat50nt,$Skins-cPat50nt,$Closest-cPat50nt,#Skins-cPat40nt,#Closests-cPat50nt,CTP1-cPat40nt,CTP2-cPat40nt"
    Public Const cFinanceFields As String = "PayLD,Paid,LD Paid-cPat50,LD Balance-cPat50nt,DatePaid-cPat170nt,PayEOY,EOY Paid-cPat50,EOY Balance-cPat50nt,EOY DatePd-cPat170nt"
    Public Const cLDFields As String = "Paid,AmtPaid,TotAmt,Balance"
    Public Const DATE_FORMAT As String = "M/d/yyyy h:mm:ss tt"

    Public sMatchFields = New List(Of String)("Points,Team_Points,Opponent".Split(","))
End Module
