Public Class Constants
    Public Const CTP1 As String = "CTP_1"
    Public Const CTP2 As String = "CTP_2"
    Public Const skinscol As String = "SkinsCollected"
    Public Const skinsearn As String = "SkinsEarned"
    Public Const skinsextr As String = "SkinsExtra"
    Public Const ctpf1col As String = "CTPF1Collected"
    Public Const ctpf1earn As String = "CTPF1Earned"
    Public Const ctpf1extr As String = "CTPF1Extra"
    Public Const ctpf2col As String = "CTPF2Collected"
    Public Const ctpf2earn As String = "CTPF2Earned"
    Public Const ctpf2extr As String = "CTPF2Extra"
    Public Const ctpb1col As String = "CTPB1Collected"
    Public Const ctpb1earn As String = "CTPB1Earned"
    Public Const ctpb1extr As String = "CTPB1Extra"
    Public Const ctpb2col As String = "CTPB2Collected"
    Public Const ctpb2earn As String = "CTPB2Earned"
    Public Const ctpb2extr As String = "CTPB2Extra"
    Public Const kitty As String = "Kitty"

End Class
